//! Assembles the generated facade header from the resolved plan.

use crate::api::CEnumAlias;
use crate::patterns::{
    adapter_limits, byte_pair, constants, descriptor, descriptor_async, device_events, future_poll,
    handle_array, handles, label, map_async, shader_wgsl, strings, sync, typed_pair, write_texture,
};
use crate::plan::{Chunk, Plan};

const PREAMBLE: &str = "/*\n * subscript-typegpu.h — generated by `subscript-typegpu-webgpu-gen` from `webgpu.yml`\n * plus `policy.toml`.\n * Regenerate with `tools/regen.sh`; never hand-edit\n * (the byte-identical regeneration gate enforces this).\n *\n * The facade shape rules (facade.md, facade-generator.md): opaque handles only, futures as plain\n * uint64_t, no by-value structs, no callbacks, no unions, no chained\n * structs, no constants >= 2^53. Every construct here must be mapped\n * by `subscript bind` without loss.\n */\n#ifndef SUBSCRIPT_TYPEGPU_H_\n#define SUBSCRIPT_TYPEGPU_H_\n\n#include <stdbool.h>\n#include <stddef.h>\n#include <stdint.h>\n\n/*\n * `_Nullable` is a Clang qualifier, and `subscript bind` reads the\n * annotation from Clang. Every other compiler rejects the token, MSVC\n * `cl` included, so the header removes it there.\n */\n#if defined(__clang__)\n#pragma clang diagnostic ignored \"-Wnullability-completeness\"\n#else\n#define _Nullable\n#endif\n\n";

struct Item {
    comment: Option<String>,
    decl: String,
}

impl Item {
    fn new(comment: Option<String>, decl: String) -> Self {
        Item { comment, decl }
    }
}

fn line_comment(doc: &str) -> String {
    format!("/* {doc} */")
}

pub(crate) fn render(plan: &Plan, cenum_aliases: &[CEnumAlias]) -> String {
    let has_async = plan.chunks.iter().any(|chunk| {
        matches!(
            chunk,
            Chunk::Async(_)
                | Chunk::DescriptorAsync(_)
                | Chunk::MapAsync(_)
                | Chunk::DeviceEvents(_)
        )
    });
    let mut out = String::from(PREAMBLE);

    for object in &plan.objects {
        out.push_str(&handles::c_typedef(object));
        out.push('\n');
    }
    for set in &plan.const_sets {
        out.push('\n');
        out.push_str(&constants::c_const_set(set));
        let boundary_name = crate::naming::subscript_typegpu_type(&set.name);
        if let Some(alias) = cenum_aliases
            .iter()
            .find(|alias| alias.boundary_name == boundary_name)
        {
            out.push_str(&format!(
                "\n/* @subscript-cenum {} {} */",
                alias.boundary_name, alias.public_name
            ));
        }
        out.push('\n');
    }
    if plan.needs_string_view {
        out.push('\n');
        out.push_str(strings::c_string_view());
        out.push('\n');
    }
    if plan.device_events {
        out.push('\n');
        out.push_str(device_events::c_records());
        out.push('\n');
    }
    if plan
        .chunks
        .iter()
        .any(|chunk| matches!(chunk, Chunk::AdapterInfo(_)))
    {
        out.push('\n');
        out.push_str(adapter_limits::c_adapter_info());
        out.push('\n');
    }
    for shape in &plan.structs {
        out.push('\n');
        out.push_str(&descriptor::c_struct(shape));
        out.push('\n');
    }
    if plan.device_descriptor {
        out.push('\n');
        out.push_str(adapter_limits::c_device_descriptor());
        out.push('\n');
    }
    for op in plan.chunks.iter().filter_map(|chunk| match chunk {
        Chunk::ShaderWgsl(op) => Some(op),
        _ => None,
    }) {
        out.push('\n');
        out.push_str(&shader_wgsl::c_struct(op));
        out.push('\n');
    }
    if has_async {
        out.push('\n');
        out.push_str(future_poll::FUTURE_ID_COMMENT);
        out.push('\n');
        out.push_str("typedef uint64_t SubscriptTypegpuFutureId;\n");
    }

    let mut chunks: Vec<Vec<Item>> = Vec::new();
    let mut creation = Vec::new();
    for create in &plan.creates {
        creation.push(Item::new(
            create.doc.as_deref().map(line_comment),
            sync::c_create_decl(create),
        ));
    }
    for op in &plan.anchor_syncs {
        creation.push(Item::new(None, sync::c_sync_decl(op)));
    }
    creation.push(Item::new(None, handles::c_release_decl(&plan.anchor)));
    chunks.push(creation);

    for chunk in &plan.chunks {
        match chunk {
            Chunk::Async(op) if op.first => {
                chunks.push(vec![Item::new(
                    None,
                    future_poll::c_request_decl(op, &plan.anchor),
                )]);
                chunks.push(vec![
                    Item::new(
                        Some(future_poll::COMPLETED_COMMENT.to_string()),
                        future_poll::c_completed_decl(&plan.anchor),
                    ),
                    Item::new(None, future_poll::c_drop_decl(&plan.anchor)),
                ]);
                if let Some(take) = future_poll::c_take_decl(op, &plan.anchor) {
                    chunks.push(vec![Item::new(
                        Some(future_poll::TAKE_COMMENT.to_string()),
                        take,
                    )]);
                }
            }
            Chunk::Async(op) => {
                let mut items = vec![Item::new(
                    None,
                    future_poll::c_request_decl(op, &plan.anchor),
                )];
                if let Some(decl) = future_poll::c_request_descriptor_decl(op, &plan.anchor) {
                    items.push(Item::new(None, decl));
                }
                if let Some(take) = future_poll::c_take_decl(op, &plan.anchor) {
                    items.push(Item::new(None, take));
                }
                chunks.push(items);
            }
            Chunk::Sync(op) => chunks.push(vec![Item::new(None, sync::c_sync_decl(op))]),
            Chunk::Descriptor(op) => {
                let shape = plan
                    .structs
                    .iter()
                    .find(|shape| shape.source == op.descriptor)
                    .expect("descriptor shape exists");
                chunks.push(vec![Item::new(None, descriptor::c_decl(op, shape))]);
            }
            Chunk::DescriptorAsync(op) => {
                let shape = plan
                    .structs
                    .iter()
                    .find(|shape| shape.source == op.descriptor)
                    .expect("descriptor shape exists");
                let mut items = vec![Item::new(
                    None,
                    descriptor_async::c_request_decl(op, shape, &plan.anchor),
                )];
                if let Some(take) = future_poll::c_take_decl(&op.async_op, &plan.anchor) {
                    items.push(Item::new(None, take));
                }
                chunks.push(items);
            }
            Chunk::ShaderWgsl(op) => {
                chunks.push(vec![Item::new(None, shader_wgsl::c_decl(op))]);
            }
            Chunk::Label(op) => chunks.push(vec![Item::new(None, label::c_decl(op))]),
            Chunk::BytePair(op) => {
                chunks.push(vec![Item::new(None, byte_pair::c_decl(op))]);
            }
            Chunk::TypedPair(op) => {
                chunks.push(vec![Item::new(
                    Some(typed_pair::c_comment(op)),
                    typed_pair::c_decl(op),
                )]);
            }
            Chunk::Array(op) => {
                chunks.push(vec![Item::new(None, handle_array::c_decl(op))]);
            }
            Chunk::MapAsync(op) => chunks.push(
                map_async::c_decls(op)
                    .into_iter()
                    .map(|decl| Item::new(None, decl))
                    .collect(),
            ),
            Chunk::WriteTexture(op) => {
                let find = |name: &str| {
                    plan.structs
                        .iter()
                        .find(|shape| shape.source == name)
                        .expect("write-texture shape exists")
                };
                chunks.push(vec![Item::new(
                    None,
                    write_texture::c_decl(
                        op,
                        find(&op.destination),
                        find(&op.layout),
                        find(&op.extent),
                    ),
                )]);
            }
            Chunk::DeviceEvents(op) => {
                chunks.push(
                    device_events::c_decls(op, &plan.anchor)
                        .into_iter()
                        .map(|decl| Item::new(None, decl))
                        .collect(),
                );
            }
            Chunk::Limits(op) => {
                let shape = plan
                    .structs
                    .iter()
                    .find(|shape| shape.source == op.shape)
                    .expect("limits shape exists");
                chunks.push(vec![Item::new(
                    None,
                    adapter_limits::c_limits_decl(op, shape),
                )]);
            }
            Chunk::AdapterInfo(op) => {
                chunks.push(vec![Item::new(None, adapter_limits::c_info_decl(op))])
            }
            Chunk::Feature(op) => {
                chunks.push(vec![Item::new(None, adapter_limits::c_feature_decl(op))])
            }
        }
    }

    let releases: Vec<Item> = plan
        .objects
        .iter()
        .rev()
        .filter(|object| **object != plan.anchor)
        .map(|object| Item::new(None, handles::c_release_decl(object)))
        .collect();
    if !releases.is_empty() {
        chunks.push(releases);
    }

    for chunk in &chunks {
        out.push('\n');
        for item in chunk {
            if let Some(comment) = &item.comment {
                out.push_str(comment);
                out.push('\n');
            }
            out.push_str(&item.decl);
            out.push('\n');
        }
    }
    out.push_str("\n#endif /* SUBSCRIPT_TYPEGPU_H_ */\n");
    out
}
