/*
 * subscript-typegpu.h — generated by `subscript-typegpu-webgpu-gen` from `webgpu.yml`
 * plus `policy.toml`.
 * Regenerate with `tools/regen.sh`; never hand-edit
 * (the byte-identical regeneration gate enforces this).
 *
 * The facade shape rules (facade.md, facade-generator.md): opaque handles only, futures as plain
 * uint64_t, no by-value structs, no callbacks, no unions, no chained
 * structs, no constants >= 2^53. Every construct here must be mapped
 * by `subscript bind` without loss.
 */
#ifndef SUBSCRIPT_TYPEGPU_H_
#define SUBSCRIPT_TYPEGPU_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/*
 * `_Nullable` is a Clang qualifier, and `subscript bind` reads the
 * annotation from Clang. Every other compiler rejects the token, MSVC
 * `cl` included, so the header removes it there.
 */
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wnullability-completeness"
#else
#define _Nullable
#endif

typedef struct SubscriptTypegpuInstanceImpl* SubscriptTypegpuInstance;
typedef struct SubscriptTypegpuAdapterImpl* SubscriptTypegpuAdapter;
typedef struct SubscriptTypegpuDeviceImpl* SubscriptTypegpuDevice;
typedef struct SubscriptTypegpuQueueImpl* SubscriptTypegpuQueue;
typedef struct SubscriptTypegpuBufferImpl* SubscriptTypegpuBuffer;
typedef struct SubscriptTypegpuTextureImpl* SubscriptTypegpuTexture;
typedef struct SubscriptTypegpuTextureViewImpl* SubscriptTypegpuTextureView;
typedef struct SubscriptTypegpuSamplerImpl* SubscriptTypegpuSampler;
typedef struct SubscriptTypegpuBindGroupLayoutImpl* SubscriptTypegpuBindGroupLayout;
typedef struct SubscriptTypegpuBindGroupImpl* SubscriptTypegpuBindGroup;
typedef struct SubscriptTypegpuPipelineLayoutImpl* SubscriptTypegpuPipelineLayout;
typedef struct SubscriptTypegpuShaderModuleImpl* SubscriptTypegpuShaderModule;
typedef struct SubscriptTypegpuComputePipelineImpl* SubscriptTypegpuComputePipeline;
typedef struct SubscriptTypegpuRenderPipelineImpl* SubscriptTypegpuRenderPipeline;
typedef struct SubscriptTypegpuCommandEncoderImpl* SubscriptTypegpuCommandEncoder;
typedef struct SubscriptTypegpuComputePassEncoderImpl* SubscriptTypegpuComputePassEncoder;
typedef struct SubscriptTypegpuRenderPassEncoderImpl* SubscriptTypegpuRenderPassEncoder;
typedef struct SubscriptTypegpuCommandBufferImpl* SubscriptTypegpuCommandBuffer;
typedef struct SubscriptTypegpuRenderBundleEncoderImpl* SubscriptTypegpuRenderBundleEncoder;
typedef struct SubscriptTypegpuRenderBundleImpl* SubscriptTypegpuRenderBundle;
typedef struct SubscriptTypegpuQuerySetImpl* SubscriptTypegpuQuerySet;

typedef uint64_t SubscriptTypegpuBufferUsage;
static const SubscriptTypegpuBufferUsage SUBSCRIPT_TYPEGPU_BUFFER_USAGE_NONE = 0x0;
static const SubscriptTypegpuBufferUsage SUBSCRIPT_TYPEGPU_BUFFER_USAGE_MAP_READ = 0x1;
static const SubscriptTypegpuBufferUsage SUBSCRIPT_TYPEGPU_BUFFER_USAGE_MAP_WRITE = 0x2;
static const SubscriptTypegpuBufferUsage SUBSCRIPT_TYPEGPU_BUFFER_USAGE_COPY_SRC = 0x4;
static const SubscriptTypegpuBufferUsage SUBSCRIPT_TYPEGPU_BUFFER_USAGE_COPY_DST = 0x8;
static const SubscriptTypegpuBufferUsage SUBSCRIPT_TYPEGPU_BUFFER_USAGE_INDEX = 0x10;
static const SubscriptTypegpuBufferUsage SUBSCRIPT_TYPEGPU_BUFFER_USAGE_VERTEX = 0x20;
static const SubscriptTypegpuBufferUsage SUBSCRIPT_TYPEGPU_BUFFER_USAGE_UNIFORM = 0x40;
static const SubscriptTypegpuBufferUsage SUBSCRIPT_TYPEGPU_BUFFER_USAGE_STORAGE = 0x80;
static const SubscriptTypegpuBufferUsage SUBSCRIPT_TYPEGPU_BUFFER_USAGE_INDIRECT = 0x100;
static const SubscriptTypegpuBufferUsage SUBSCRIPT_TYPEGPU_BUFFER_USAGE_QUERY_RESOLVE = 0x200;

typedef uint64_t SubscriptTypegpuMapMode;
static const SubscriptTypegpuMapMode SUBSCRIPT_TYPEGPU_MAP_MODE_NONE = 0x0;
static const SubscriptTypegpuMapMode SUBSCRIPT_TYPEGPU_MAP_MODE_READ = 0x1;
static const SubscriptTypegpuMapMode SUBSCRIPT_TYPEGPU_MAP_MODE_WRITE = 0x2;

typedef enum SubscriptTypegpuBufferMapState {
    SUBSCRIPT_TYPEGPU_BUFFER_MAP_STATE_UNMAPPED = 0x00000001,
    SUBSCRIPT_TYPEGPU_BUFFER_MAP_STATE_PENDING = 0x00000002,
    SUBSCRIPT_TYPEGPU_BUFFER_MAP_STATE_MAPPED = 0x00000003,
} SubscriptTypegpuBufferMapState;
/* @subscript-cenum SubscriptTypegpuBufferMapState GPUBufferMapState */

typedef uint64_t SubscriptTypegpuTextureUsage;
static const SubscriptTypegpuTextureUsage SUBSCRIPT_TYPEGPU_TEXTURE_USAGE_NONE = 0x0;
static const SubscriptTypegpuTextureUsage SUBSCRIPT_TYPEGPU_TEXTURE_USAGE_COPY_SRC = 0x1;
static const SubscriptTypegpuTextureUsage SUBSCRIPT_TYPEGPU_TEXTURE_USAGE_COPY_DST = 0x2;
static const SubscriptTypegpuTextureUsage SUBSCRIPT_TYPEGPU_TEXTURE_USAGE_TEXTURE_BINDING = 0x4;
static const SubscriptTypegpuTextureUsage SUBSCRIPT_TYPEGPU_TEXTURE_USAGE_STORAGE_BINDING = 0x8;
static const SubscriptTypegpuTextureUsage SUBSCRIPT_TYPEGPU_TEXTURE_USAGE_RENDER_ATTACHMENT = 0x10;
static const SubscriptTypegpuTextureUsage SUBSCRIPT_TYPEGPU_TEXTURE_USAGE_TRANSIENT_ATTACHMENT = 0x20;

typedef enum SubscriptTypegpuTextureDimension {
    SUBSCRIPT_TYPEGPU_TEXTURE_DIMENSION_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_TEXTURE_DIMENSION_1_D = 0x00000001,
    SUBSCRIPT_TYPEGPU_TEXTURE_DIMENSION_2_D = 0x00000002,
    SUBSCRIPT_TYPEGPU_TEXTURE_DIMENSION_3_D = 0x00000003,
} SubscriptTypegpuTextureDimension;
/* @subscript-cenum SubscriptTypegpuTextureDimension GPUTextureDimension */

typedef enum SubscriptTypegpuTextureFormat {
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_R8_UNORM = 0x00000001,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_R8_SNORM = 0x00000002,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_R8_UINT = 0x00000003,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_R8_SINT = 0x00000004,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_R16_UNORM = 0x00000005,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_R16_SNORM = 0x00000006,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_R16_UINT = 0x00000007,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_R16_SINT = 0x00000008,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_R16_FLOAT = 0x00000009,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RG8_UNORM = 0x0000000A,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RG8_SNORM = 0x0000000B,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RG8_UINT = 0x0000000C,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RG8_SINT = 0x0000000D,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_R32_FLOAT = 0x0000000E,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_R32_UINT = 0x0000000F,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_R32_SINT = 0x00000010,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RG16_UNORM = 0x00000011,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RG16_SNORM = 0x00000012,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RG16_UINT = 0x00000013,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RG16_SINT = 0x00000014,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RG16_FLOAT = 0x00000015,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGBA8_UNORM = 0x00000016,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGBA8_UNORM_SRGB = 0x00000017,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGBA8_SNORM = 0x00000018,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGBA8_UINT = 0x00000019,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGBA8_SINT = 0x0000001A,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BGRA8_UNORM = 0x0000001B,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BGRA8_UNORM_SRGB = 0x0000001C,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGB10_A2_UINT = 0x0000001D,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGB10_A2_UNORM = 0x0000001E,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RG11_B10_UFLOAT = 0x0000001F,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGB9_E5_UFLOAT = 0x00000020,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RG32_FLOAT = 0x00000021,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RG32_UINT = 0x00000022,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RG32_SINT = 0x00000023,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGBA16_UNORM = 0x00000024,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGBA16_SNORM = 0x00000025,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGBA16_UINT = 0x00000026,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGBA16_SINT = 0x00000027,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGBA16_FLOAT = 0x00000028,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGBA32_FLOAT = 0x00000029,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGBA32_UINT = 0x0000002A,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_RGBA32_SINT = 0x0000002B,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_STENCIL8 = 0x0000002C,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_DEPTH16_UNORM = 0x0000002D,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_DEPTH24_PLUS = 0x0000002E,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_DEPTH24_PLUS_STENCIL8 = 0x0000002F,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_DEPTH32_FLOAT = 0x00000030,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_DEPTH32_FLOAT_STENCIL8 = 0x00000031,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC1_RGBA_UNORM = 0x00000032,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC1_RGBA_UNORM_SRGB = 0x00000033,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC2_RGBA_UNORM = 0x00000034,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC2_RGBA_UNORM_SRGB = 0x00000035,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC3_RGBA_UNORM = 0x00000036,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC3_RGBA_UNORM_SRGB = 0x00000037,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC4_R_UNORM = 0x00000038,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC4_R_SNORM = 0x00000039,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC5_RG_UNORM = 0x0000003A,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC5_RG_SNORM = 0x0000003B,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC6_HRGB_UFLOAT = 0x0000003C,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC6_HRGB_FLOAT = 0x0000003D,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC7_RGBA_UNORM = 0x0000003E,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_BC7_RGBA_UNORM_SRGB = 0x0000003F,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ETC2_RGB8_UNORM = 0x00000040,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ETC2_RGB8_UNORM_SRGB = 0x00000041,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ETC2_RGB8_A1_UNORM = 0x00000042,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ETC2_RGB8_A1_UNORM_SRGB = 0x00000043,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ETC2_RGBA8_UNORM = 0x00000044,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ETC2_RGBA8_UNORM_SRGB = 0x00000045,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_EACR11_UNORM = 0x00000046,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_EACR11_SNORM = 0x00000047,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_EACRG11_UNORM = 0x00000048,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_EACRG11_SNORM = 0x00000049,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC4X4_UNORM = 0x0000004A,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC4X4_UNORM_SRGB = 0x0000004B,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC5X4_UNORM = 0x0000004C,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC5X4_UNORM_SRGB = 0x0000004D,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC5X5_UNORM = 0x0000004E,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC5X5_UNORM_SRGB = 0x0000004F,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC6X5_UNORM = 0x00000050,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC6X5_UNORM_SRGB = 0x00000051,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC6X6_UNORM = 0x00000052,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC6X6_UNORM_SRGB = 0x00000053,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC8X5_UNORM = 0x00000054,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC8X5_UNORM_SRGB = 0x00000055,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC8X6_UNORM = 0x00000056,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC8X6_UNORM_SRGB = 0x00000057,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC8X8_UNORM = 0x00000058,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC8X8_UNORM_SRGB = 0x00000059,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC10X5_UNORM = 0x0000005A,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC10X5_UNORM_SRGB = 0x0000005B,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC10X6_UNORM = 0x0000005C,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC10X6_UNORM_SRGB = 0x0000005D,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC10X8_UNORM = 0x0000005E,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC10X8_UNORM_SRGB = 0x0000005F,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC10X10_UNORM = 0x00000060,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC10X10_UNORM_SRGB = 0x00000061,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC12X10_UNORM = 0x00000062,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC12X10_UNORM_SRGB = 0x00000063,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC12X12_UNORM = 0x00000064,
    SUBSCRIPT_TYPEGPU_TEXTURE_FORMAT_ASTC12X12_UNORM_SRGB = 0x00000065,
} SubscriptTypegpuTextureFormat;
/* @subscript-cenum SubscriptTypegpuTextureFormat GPUTextureFormat */

typedef enum SubscriptTypegpuTextureViewDimension {
    SUBSCRIPT_TYPEGPU_TEXTURE_VIEW_DIMENSION_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_TEXTURE_VIEW_DIMENSION_1_D = 0x00000001,
    SUBSCRIPT_TYPEGPU_TEXTURE_VIEW_DIMENSION_2_D = 0x00000002,
    SUBSCRIPT_TYPEGPU_TEXTURE_VIEW_DIMENSION_2_D_ARRAY = 0x00000003,
    SUBSCRIPT_TYPEGPU_TEXTURE_VIEW_DIMENSION_CUBE = 0x00000004,
    SUBSCRIPT_TYPEGPU_TEXTURE_VIEW_DIMENSION_CUBE_ARRAY = 0x00000005,
    SUBSCRIPT_TYPEGPU_TEXTURE_VIEW_DIMENSION_3_D = 0x00000006,
} SubscriptTypegpuTextureViewDimension;
/* @subscript-cenum SubscriptTypegpuTextureViewDimension GPUTextureViewDimension */

typedef enum SubscriptTypegpuTextureAspect {
    SUBSCRIPT_TYPEGPU_TEXTURE_ASPECT_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_TEXTURE_ASPECT_ALL = 0x00000001,
    SUBSCRIPT_TYPEGPU_TEXTURE_ASPECT_STENCIL_ONLY = 0x00000002,
    SUBSCRIPT_TYPEGPU_TEXTURE_ASPECT_DEPTH_ONLY = 0x00000003,
} SubscriptTypegpuTextureAspect;
/* @subscript-cenum SubscriptTypegpuTextureAspect GPUTextureAspect */

typedef enum SubscriptTypegpuAddressMode {
    SUBSCRIPT_TYPEGPU_ADDRESS_MODE_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_ADDRESS_MODE_CLAMP_TO_EDGE = 0x00000001,
    SUBSCRIPT_TYPEGPU_ADDRESS_MODE_REPEAT = 0x00000002,
    SUBSCRIPT_TYPEGPU_ADDRESS_MODE_MIRROR_REPEAT = 0x00000003,
} SubscriptTypegpuAddressMode;
/* @subscript-cenum SubscriptTypegpuAddressMode GPUAddressMode */

typedef enum SubscriptTypegpuFilterMode {
    SUBSCRIPT_TYPEGPU_FILTER_MODE_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_FILTER_MODE_NEAREST = 0x00000001,
    SUBSCRIPT_TYPEGPU_FILTER_MODE_LINEAR = 0x00000002,
} SubscriptTypegpuFilterMode;
/* @subscript-cenum SubscriptTypegpuFilterMode GPUFilterMode */

typedef enum SubscriptTypegpuMipmapFilterMode {
    SUBSCRIPT_TYPEGPU_MIPMAP_FILTER_MODE_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_MIPMAP_FILTER_MODE_NEAREST = 0x00000001,
    SUBSCRIPT_TYPEGPU_MIPMAP_FILTER_MODE_LINEAR = 0x00000002,
} SubscriptTypegpuMipmapFilterMode;
/* @subscript-cenum SubscriptTypegpuMipmapFilterMode GPUMipmapFilterMode */

typedef enum SubscriptTypegpuCompareFunction {
    SUBSCRIPT_TYPEGPU_COMPARE_FUNCTION_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_COMPARE_FUNCTION_NEVER = 0x00000001,
    SUBSCRIPT_TYPEGPU_COMPARE_FUNCTION_LESS = 0x00000002,
    SUBSCRIPT_TYPEGPU_COMPARE_FUNCTION_EQUAL = 0x00000003,
    SUBSCRIPT_TYPEGPU_COMPARE_FUNCTION_LESS_EQUAL = 0x00000004,
    SUBSCRIPT_TYPEGPU_COMPARE_FUNCTION_GREATER = 0x00000005,
    SUBSCRIPT_TYPEGPU_COMPARE_FUNCTION_NOT_EQUAL = 0x00000006,
    SUBSCRIPT_TYPEGPU_COMPARE_FUNCTION_GREATER_EQUAL = 0x00000007,
    SUBSCRIPT_TYPEGPU_COMPARE_FUNCTION_ALWAYS = 0x00000008,
} SubscriptTypegpuCompareFunction;
/* @subscript-cenum SubscriptTypegpuCompareFunction GPUCompareFunction */

typedef uint64_t SubscriptTypegpuShaderStage;
static const SubscriptTypegpuShaderStage SUBSCRIPT_TYPEGPU_SHADER_STAGE_NONE = 0x0;
static const SubscriptTypegpuShaderStage SUBSCRIPT_TYPEGPU_SHADER_STAGE_VERTEX = 0x1;
static const SubscriptTypegpuShaderStage SUBSCRIPT_TYPEGPU_SHADER_STAGE_FRAGMENT = 0x2;
static const SubscriptTypegpuShaderStage SUBSCRIPT_TYPEGPU_SHADER_STAGE_COMPUTE = 0x4;

typedef enum SubscriptTypegpuBufferBindingType {
    SUBSCRIPT_TYPEGPU_BUFFER_BINDING_TYPE_BINDING_NOT_USED = 0x00000000,
    SUBSCRIPT_TYPEGPU_BUFFER_BINDING_TYPE_UNDEFINED = 0x00000001,
    SUBSCRIPT_TYPEGPU_BUFFER_BINDING_TYPE_UNIFORM = 0x00000002,
    SUBSCRIPT_TYPEGPU_BUFFER_BINDING_TYPE_STORAGE = 0x00000003,
    SUBSCRIPT_TYPEGPU_BUFFER_BINDING_TYPE_READ_ONLY_STORAGE = 0x00000004,
} SubscriptTypegpuBufferBindingType;
/* @subscript-cenum SubscriptTypegpuBufferBindingType GPUBufferBindingType */

typedef enum SubscriptTypegpuSamplerBindingType {
    SUBSCRIPT_TYPEGPU_SAMPLER_BINDING_TYPE_BINDING_NOT_USED = 0x00000000,
    SUBSCRIPT_TYPEGPU_SAMPLER_BINDING_TYPE_UNDEFINED = 0x00000001,
    SUBSCRIPT_TYPEGPU_SAMPLER_BINDING_TYPE_FILTERING = 0x00000002,
    SUBSCRIPT_TYPEGPU_SAMPLER_BINDING_TYPE_NON_FILTERING = 0x00000003,
    SUBSCRIPT_TYPEGPU_SAMPLER_BINDING_TYPE_COMPARISON = 0x00000004,
} SubscriptTypegpuSamplerBindingType;
/* @subscript-cenum SubscriptTypegpuSamplerBindingType GPUSamplerBindingType */

typedef enum SubscriptTypegpuTextureSampleType {
    SUBSCRIPT_TYPEGPU_TEXTURE_SAMPLE_TYPE_BINDING_NOT_USED = 0x00000000,
    SUBSCRIPT_TYPEGPU_TEXTURE_SAMPLE_TYPE_UNDEFINED = 0x00000001,
    SUBSCRIPT_TYPEGPU_TEXTURE_SAMPLE_TYPE_FLOAT = 0x00000002,
    SUBSCRIPT_TYPEGPU_TEXTURE_SAMPLE_TYPE_UNFILTERABLE_FLOAT = 0x00000003,
    SUBSCRIPT_TYPEGPU_TEXTURE_SAMPLE_TYPE_DEPTH = 0x00000004,
    SUBSCRIPT_TYPEGPU_TEXTURE_SAMPLE_TYPE_SINT = 0x00000005,
    SUBSCRIPT_TYPEGPU_TEXTURE_SAMPLE_TYPE_UINT = 0x00000006,
} SubscriptTypegpuTextureSampleType;
/* @subscript-cenum SubscriptTypegpuTextureSampleType GPUTextureSampleType */

typedef enum SubscriptTypegpuStorageTextureAccess {
    SUBSCRIPT_TYPEGPU_STORAGE_TEXTURE_ACCESS_BINDING_NOT_USED = 0x00000000,
    SUBSCRIPT_TYPEGPU_STORAGE_TEXTURE_ACCESS_UNDEFINED = 0x00000001,
    SUBSCRIPT_TYPEGPU_STORAGE_TEXTURE_ACCESS_WRITE_ONLY = 0x00000002,
    SUBSCRIPT_TYPEGPU_STORAGE_TEXTURE_ACCESS_READ_ONLY = 0x00000003,
    SUBSCRIPT_TYPEGPU_STORAGE_TEXTURE_ACCESS_READ_WRITE = 0x00000004,
} SubscriptTypegpuStorageTextureAccess;
/* @subscript-cenum SubscriptTypegpuStorageTextureAccess GPUStorageTextureAccess */

typedef enum SubscriptTypegpuVertexFormat {
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UINT8 = 0x00000001,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UINT8X2 = 0x00000002,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UINT8X4 = 0x00000003,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SINT8 = 0x00000004,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SINT8X2 = 0x00000005,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SINT8X4 = 0x00000006,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UNORM8 = 0x00000007,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UNORM8X2 = 0x00000008,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UNORM8X4 = 0x00000009,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SNORM8 = 0x0000000A,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SNORM8X2 = 0x0000000B,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SNORM8X4 = 0x0000000C,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UINT16 = 0x0000000D,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UINT16X2 = 0x0000000E,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UINT16X4 = 0x0000000F,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SINT16 = 0x00000010,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SINT16X2 = 0x00000011,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SINT16X4 = 0x00000012,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UNORM16 = 0x00000013,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UNORM16X2 = 0x00000014,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UNORM16X4 = 0x00000015,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SNORM16 = 0x00000016,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SNORM16X2 = 0x00000017,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SNORM16X4 = 0x00000018,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_FLOAT16 = 0x00000019,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_FLOAT16X2 = 0x0000001A,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_FLOAT16X4 = 0x0000001B,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_FLOAT32 = 0x0000001C,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_FLOAT32X2 = 0x0000001D,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_FLOAT32X3 = 0x0000001E,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_FLOAT32X4 = 0x0000001F,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UINT32 = 0x00000020,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UINT32X2 = 0x00000021,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UINT32X3 = 0x00000022,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UINT32X4 = 0x00000023,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SINT32 = 0x00000024,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SINT32X2 = 0x00000025,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SINT32X3 = 0x00000026,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_SINT32X4 = 0x00000027,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UNORM10_10_10_2 = 0x00000028,
    SUBSCRIPT_TYPEGPU_VERTEX_FORMAT_UNORM8X4_BGRA = 0x00000029,
} SubscriptTypegpuVertexFormat;
/* @subscript-cenum SubscriptTypegpuVertexFormat GPUVertexFormat */

typedef enum SubscriptTypegpuVertexStepMode {
    SUBSCRIPT_TYPEGPU_VERTEX_STEP_MODE_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_VERTEX_STEP_MODE_VERTEX = 0x00000001,
    SUBSCRIPT_TYPEGPU_VERTEX_STEP_MODE_INSTANCE = 0x00000002,
} SubscriptTypegpuVertexStepMode;
/* @subscript-cenum SubscriptTypegpuVertexStepMode GPUVertexStepMode */

typedef enum SubscriptTypegpuPrimitiveTopology {
    SUBSCRIPT_TYPEGPU_PRIMITIVE_TOPOLOGY_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_PRIMITIVE_TOPOLOGY_POINT_LIST = 0x00000001,
    SUBSCRIPT_TYPEGPU_PRIMITIVE_TOPOLOGY_LINE_LIST = 0x00000002,
    SUBSCRIPT_TYPEGPU_PRIMITIVE_TOPOLOGY_LINE_STRIP = 0x00000003,
    SUBSCRIPT_TYPEGPU_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = 0x00000004,
    SUBSCRIPT_TYPEGPU_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP = 0x00000005,
} SubscriptTypegpuPrimitiveTopology;
/* @subscript-cenum SubscriptTypegpuPrimitiveTopology GPUPrimitiveTopology */

typedef enum SubscriptTypegpuIndexFormat {
    SUBSCRIPT_TYPEGPU_INDEX_FORMAT_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_INDEX_FORMAT_UINT16 = 0x00000001,
    SUBSCRIPT_TYPEGPU_INDEX_FORMAT_UINT32 = 0x00000002,
} SubscriptTypegpuIndexFormat;
/* @subscript-cenum SubscriptTypegpuIndexFormat GPUIndexFormat */

typedef enum SubscriptTypegpuFrontFace {
    SUBSCRIPT_TYPEGPU_FRONT_FACE_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_FRONT_FACE_CCW = 0x00000001,
    SUBSCRIPT_TYPEGPU_FRONT_FACE_CW = 0x00000002,
} SubscriptTypegpuFrontFace;
/* @subscript-cenum SubscriptTypegpuFrontFace GPUFrontFace */

typedef enum SubscriptTypegpuCullMode {
    SUBSCRIPT_TYPEGPU_CULL_MODE_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_CULL_MODE_NONE = 0x00000001,
    SUBSCRIPT_TYPEGPU_CULL_MODE_FRONT = 0x00000002,
    SUBSCRIPT_TYPEGPU_CULL_MODE_BACK = 0x00000003,
} SubscriptTypegpuCullMode;
/* @subscript-cenum SubscriptTypegpuCullMode GPUCullMode */

typedef enum SubscriptTypegpuBlendOperation {
    SUBSCRIPT_TYPEGPU_BLEND_OPERATION_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_BLEND_OPERATION_ADD = 0x00000001,
    SUBSCRIPT_TYPEGPU_BLEND_OPERATION_SUBTRACT = 0x00000002,
    SUBSCRIPT_TYPEGPU_BLEND_OPERATION_REVERSE_SUBTRACT = 0x00000003,
    SUBSCRIPT_TYPEGPU_BLEND_OPERATION_MIN = 0x00000004,
    SUBSCRIPT_TYPEGPU_BLEND_OPERATION_MAX = 0x00000005,
} SubscriptTypegpuBlendOperation;
/* @subscript-cenum SubscriptTypegpuBlendOperation GPUBlendOperation */

typedef enum SubscriptTypegpuBlendFactor {
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_ZERO = 0x00000001,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_ONE = 0x00000002,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_SRC = 0x00000003,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_ONE_MINUS_SRC = 0x00000004,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_SRC_ALPHA = 0x00000005,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA = 0x00000006,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_DST = 0x00000007,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_ONE_MINUS_DST = 0x00000008,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_DST_ALPHA = 0x00000009,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_ONE_MINUS_DST_ALPHA = 0x0000000A,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_SRC_ALPHA_SATURATED = 0x0000000B,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_CONSTANT = 0x0000000C,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_ONE_MINUS_CONSTANT = 0x0000000D,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_SRC1 = 0x0000000E,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_ONE_MINUS_SRC1 = 0x0000000F,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_SRC1_ALPHA = 0x00000010,
    SUBSCRIPT_TYPEGPU_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA = 0x00000011,
} SubscriptTypegpuBlendFactor;
/* @subscript-cenum SubscriptTypegpuBlendFactor GPUBlendFactor */

typedef uint64_t SubscriptTypegpuColorWriteMask;
static const SubscriptTypegpuColorWriteMask SUBSCRIPT_TYPEGPU_COLOR_WRITE_MASK_NONE = 0x0;
static const SubscriptTypegpuColorWriteMask SUBSCRIPT_TYPEGPU_COLOR_WRITE_MASK_RED = 0x1;
static const SubscriptTypegpuColorWriteMask SUBSCRIPT_TYPEGPU_COLOR_WRITE_MASK_GREEN = 0x2;
static const SubscriptTypegpuColorWriteMask SUBSCRIPT_TYPEGPU_COLOR_WRITE_MASK_BLUE = 0x4;
static const SubscriptTypegpuColorWriteMask SUBSCRIPT_TYPEGPU_COLOR_WRITE_MASK_ALPHA = 0x8;
static const SubscriptTypegpuColorWriteMask SUBSCRIPT_TYPEGPU_COLOR_WRITE_MASK_ALL = 0xF;

typedef enum SubscriptTypegpuOptionalBool {
    SUBSCRIPT_TYPEGPU_OPTIONAL_BOOL_FALSE = 0x00000000,
    SUBSCRIPT_TYPEGPU_OPTIONAL_BOOL_TRUE = 0x00000001,
    SUBSCRIPT_TYPEGPU_OPTIONAL_BOOL_UNDEFINED = 0x00000002,
} SubscriptTypegpuOptionalBool;

typedef enum SubscriptTypegpuStencilOperation {
    SUBSCRIPT_TYPEGPU_STENCIL_OPERATION_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_STENCIL_OPERATION_KEEP = 0x00000001,
    SUBSCRIPT_TYPEGPU_STENCIL_OPERATION_ZERO = 0x00000002,
    SUBSCRIPT_TYPEGPU_STENCIL_OPERATION_REPLACE = 0x00000003,
    SUBSCRIPT_TYPEGPU_STENCIL_OPERATION_INVERT = 0x00000004,
    SUBSCRIPT_TYPEGPU_STENCIL_OPERATION_INCREMENT_CLAMP = 0x00000005,
    SUBSCRIPT_TYPEGPU_STENCIL_OPERATION_DECREMENT_CLAMP = 0x00000006,
    SUBSCRIPT_TYPEGPU_STENCIL_OPERATION_INCREMENT_WRAP = 0x00000007,
    SUBSCRIPT_TYPEGPU_STENCIL_OPERATION_DECREMENT_WRAP = 0x00000008,
} SubscriptTypegpuStencilOperation;
/* @subscript-cenum SubscriptTypegpuStencilOperation GPUStencilOperation */

typedef enum SubscriptTypegpuLoadOp {
    SUBSCRIPT_TYPEGPU_LOAD_OP_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_LOAD_OP_LOAD = 0x00000001,
    SUBSCRIPT_TYPEGPU_LOAD_OP_CLEAR = 0x00000002,
} SubscriptTypegpuLoadOp;
/* @subscript-cenum SubscriptTypegpuLoadOp GPULoadOp */

typedef enum SubscriptTypegpuStoreOp {
    SUBSCRIPT_TYPEGPU_STORE_OP_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_STORE_OP_STORE = 0x00000001,
    SUBSCRIPT_TYPEGPU_STORE_OP_DISCARD = 0x00000002,
} SubscriptTypegpuStoreOp;
/* @subscript-cenum SubscriptTypegpuStoreOp GPUStoreOp */

typedef enum SubscriptTypegpuQueryType {
    SUBSCRIPT_TYPEGPU_QUERY_TYPE_OCCLUSION = 0x00000001,
    SUBSCRIPT_TYPEGPU_QUERY_TYPE_TIMESTAMP = 0x00000002,
} SubscriptTypegpuQueryType;
/* @subscript-cenum SubscriptTypegpuQueryType GPUQueryType */

typedef enum SubscriptTypegpuErrorFilter {
    SUBSCRIPT_TYPEGPU_ERROR_FILTER_VALIDATION = 0x00000001,
    SUBSCRIPT_TYPEGPU_ERROR_FILTER_OUT_OF_MEMORY = 0x00000002,
    SUBSCRIPT_TYPEGPU_ERROR_FILTER_INTERNAL = 0x00000003,
} SubscriptTypegpuErrorFilter;
/* @subscript-cenum SubscriptTypegpuErrorFilter GPUErrorFilter */

typedef enum SubscriptTypegpuErrorType {
    SUBSCRIPT_TYPEGPU_ERROR_TYPE_NO_ERROR = 0x00000001,
    SUBSCRIPT_TYPEGPU_ERROR_TYPE_VALIDATION = 0x00000002,
    SUBSCRIPT_TYPEGPU_ERROR_TYPE_OUT_OF_MEMORY = 0x00000003,
    SUBSCRIPT_TYPEGPU_ERROR_TYPE_INTERNAL = 0x00000004,
    SUBSCRIPT_TYPEGPU_ERROR_TYPE_UNKNOWN = 0x00000005,
} SubscriptTypegpuErrorType;

typedef enum SubscriptTypegpuDeviceLostReason {
    SUBSCRIPT_TYPEGPU_DEVICE_LOST_REASON_UNKNOWN = 0x00000001,
    SUBSCRIPT_TYPEGPU_DEVICE_LOST_REASON_DESTROYED = 0x00000002,
    SUBSCRIPT_TYPEGPU_DEVICE_LOST_REASON_CALLBACK_CANCELLED = 0x00000003,
    SUBSCRIPT_TYPEGPU_DEVICE_LOST_REASON_FAILED_CREATION = 0x00000004,
} SubscriptTypegpuDeviceLostReason;
/* @subscript-cenum SubscriptTypegpuDeviceLostReason GPUDeviceLostReason */

typedef enum SubscriptTypegpuFeatureName {
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_CORE_FEATURES_AND_LIMITS = 0x00000001,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_DEPTH_CLIP_CONTROL = 0x00000002,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_DEPTH32_FLOAT_STENCIL8 = 0x00000003,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_TEXTURE_COMPRESSION_BC = 0x00000004,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_TEXTURE_COMPRESSION_BC_SLICED3_D = 0x00000005,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_TEXTURE_COMPRESSION_ETC2 = 0x00000006,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_TEXTURE_COMPRESSION_ASTC = 0x00000007,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_TEXTURE_COMPRESSION_ASTC_SLICED3_D = 0x00000008,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_TIMESTAMP_QUERY = 0x00000009,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_INDIRECT_FIRST_INSTANCE = 0x0000000A,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_SHADER_F16 = 0x0000000B,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_RG11_B10_UFLOAT_RENDERABLE = 0x0000000C,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_BGRA8_UNORM_STORAGE = 0x0000000D,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_FLOAT32_FILTERABLE = 0x0000000E,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_FLOAT32_BLENDABLE = 0x0000000F,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_CLIP_DISTANCES = 0x00000010,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_DUAL_SOURCE_BLENDING = 0x00000011,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_SUBGROUPS = 0x00000012,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_TEXTURE_FORMATS_TIER1 = 0x00000013,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_TEXTURE_FORMATS_TIER2 = 0x00000014,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_PRIMITIVE_INDEX = 0x00000015,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_TEXTURE_COMPONENT_SWIZZLE = 0x00000016,
    SUBSCRIPT_TYPEGPU_FEATURE_NAME_SUBGROUP_SIZE_CONTROL = 0x00000017,
} SubscriptTypegpuFeatureName;
/* @subscript-cenum SubscriptTypegpuFeatureName GPUFeatureName */

typedef enum SubscriptTypegpuInstanceFeatureName {
    SUBSCRIPT_TYPEGPU_INSTANCE_FEATURE_NAME_TIMED_WAIT_ANY = 0x00000001,
    SUBSCRIPT_TYPEGPU_INSTANCE_FEATURE_NAME_SHADER_SOURCE_SPIRV = 0x00000002,
    SUBSCRIPT_TYPEGPU_INSTANCE_FEATURE_NAME_MULTIPLE_DEVICES_PER_ADAPTER = 0x00000003,
} SubscriptTypegpuInstanceFeatureName;

typedef enum SubscriptTypegpuBackendType {
    SUBSCRIPT_TYPEGPU_BACKEND_TYPE_UNDEFINED = 0x00000000,
    SUBSCRIPT_TYPEGPU_BACKEND_TYPE_NULL = 0x00000001,
    SUBSCRIPT_TYPEGPU_BACKEND_TYPE_WEB_GPU = 0x00000002,
    SUBSCRIPT_TYPEGPU_BACKEND_TYPE_D3_D11 = 0x00000003,
    SUBSCRIPT_TYPEGPU_BACKEND_TYPE_D3_D12 = 0x00000004,
    SUBSCRIPT_TYPEGPU_BACKEND_TYPE_METAL = 0x00000005,
    SUBSCRIPT_TYPEGPU_BACKEND_TYPE_VULKAN = 0x00000006,
    SUBSCRIPT_TYPEGPU_BACKEND_TYPE_OPEN_GL = 0x00000007,
    SUBSCRIPT_TYPEGPU_BACKEND_TYPE_OPEN_GLES = 0x00000008,
} SubscriptTypegpuBackendType;

typedef enum SubscriptTypegpuAdapterType {
    SUBSCRIPT_TYPEGPU_ADAPTER_TYPE_DISCRETE_GPU = 0x00000001,
    SUBSCRIPT_TYPEGPU_ADAPTER_TYPE_INTEGRATED_GPU = 0x00000002,
    SUBSCRIPT_TYPEGPU_ADAPTER_TYPE_CPU = 0x00000003,
    SUBSCRIPT_TYPEGPU_ADAPTER_TYPE_UNKNOWN = 0x00000004,
} SubscriptTypegpuAdapterType;

typedef struct SubscriptTypegpuStringView {
    const char* data;
    size_t length;
} SubscriptTypegpuStringView;

typedef struct SubscriptTypegpuErrorRecord {
    SubscriptTypegpuErrorType type;
    SubscriptTypegpuStringView message;
} SubscriptTypegpuErrorRecord;

typedef struct SubscriptTypegpuLostRecord {
    SubscriptTypegpuDeviceLostReason reason;
    SubscriptTypegpuStringView message;
} SubscriptTypegpuLostRecord;

typedef struct SubscriptTypegpuAdapterInfo {
    SubscriptTypegpuStringView vendor;
    SubscriptTypegpuStringView architecture;
    SubscriptTypegpuStringView device;
    SubscriptTypegpuStringView description;
    SubscriptTypegpuBackendType backendType;
    SubscriptTypegpuAdapterType adapterType;
    uint32_t vendorID;
    uint32_t deviceID;
} SubscriptTypegpuAdapterInfo;

typedef struct SubscriptTypegpuInstanceLimits {
    size_t timedWaitAnyMaxCount;
} SubscriptTypegpuInstanceLimits;

typedef struct SubscriptTypegpuLimits {
    uint32_t maxTextureDimension1D;
    uint32_t maxTextureDimension2D;
    uint32_t maxTextureDimension3D;
    uint32_t maxTextureArrayLayers;
    uint32_t maxBindGroups;
    uint32_t maxBindGroupsPlusVertexBuffers;
    uint32_t maxBindingsPerBindGroup;
    uint32_t maxDynamicUniformBuffersPerPipelineLayout;
    uint32_t maxDynamicStorageBuffersPerPipelineLayout;
    uint32_t maxSampledTexturesPerShaderStage;
    uint32_t maxSamplersPerShaderStage;
    uint32_t maxStorageBuffersPerShaderStage;
    uint32_t maxStorageTexturesPerShaderStage;
    uint32_t maxUniformBuffersPerShaderStage;
    uint64_t maxUniformBufferBindingSize;
    uint64_t maxStorageBufferBindingSize;
    uint32_t minUniformBufferOffsetAlignment;
    uint32_t minStorageBufferOffsetAlignment;
    uint32_t maxVertexBuffers;
    uint64_t maxBufferSize;
    uint32_t maxVertexAttributes;
    uint32_t maxVertexBufferArrayStride;
    uint32_t maxInterStageShaderVariables;
    uint32_t maxColorAttachments;
    uint32_t maxColorAttachmentBytesPerSample;
    uint32_t maxComputeWorkgroupStorageSize;
    uint32_t maxComputeInvocationsPerWorkgroup;
    uint32_t maxComputeWorkgroupSizeX;
    uint32_t maxComputeWorkgroupSizeY;
    uint32_t maxComputeWorkgroupSizeZ;
    uint32_t maxComputeWorkgroupsPerDimension;
    uint32_t maxImmediateSize;
} SubscriptTypegpuLimits;

typedef struct SubscriptTypegpuQueueDescriptor {
    SubscriptTypegpuStringView label;
} SubscriptTypegpuQueueDescriptor;

typedef struct SubscriptTypegpuBufferDescriptor {
    SubscriptTypegpuStringView label;
    SubscriptTypegpuBufferUsage usage;
    uint64_t size;
    bool mappedAtCreation;
} SubscriptTypegpuBufferDescriptor;

typedef struct SubscriptTypegpuExtent3D {
    uint32_t width;
    uint32_t height;
    uint32_t depthOrArrayLayers;
} SubscriptTypegpuExtent3D;

typedef struct SubscriptTypegpuTextureDescriptor {
    SubscriptTypegpuStringView label;
    SubscriptTypegpuTextureUsage usage;
    SubscriptTypegpuTextureDimension dimension;
    SubscriptTypegpuExtent3D size;
    SubscriptTypegpuTextureFormat format;
    uint32_t mipLevelCount;
    uint32_t sampleCount;
    size_t viewFormatsCount;
    const SubscriptTypegpuTextureFormat* viewFormats;
} SubscriptTypegpuTextureDescriptor;

typedef struct SubscriptTypegpuSamplerDescriptor {
    SubscriptTypegpuStringView label;
    SubscriptTypegpuAddressMode addressModeU;
    SubscriptTypegpuAddressMode addressModeV;
    SubscriptTypegpuAddressMode addressModeW;
    SubscriptTypegpuFilterMode magFilter;
    SubscriptTypegpuFilterMode minFilter;
    SubscriptTypegpuMipmapFilterMode mipmapFilter;
    float lodMinClamp;
    float lodMaxClamp;
    SubscriptTypegpuCompareFunction compare;
    uint16_t maxAnisotropy;
} SubscriptTypegpuSamplerDescriptor;

typedef struct SubscriptTypegpuBufferBindingLayout {
    SubscriptTypegpuBufferBindingType type;
    bool hasDynamicOffset;
    uint64_t minBindingSize;
} SubscriptTypegpuBufferBindingLayout;

typedef struct SubscriptTypegpuSamplerBindingLayout {
    SubscriptTypegpuSamplerBindingType type;
} SubscriptTypegpuSamplerBindingLayout;

typedef struct SubscriptTypegpuTextureBindingLayout {
    SubscriptTypegpuTextureSampleType sampleType;
    SubscriptTypegpuTextureViewDimension viewDimension;
    bool multisampled;
} SubscriptTypegpuTextureBindingLayout;

typedef struct SubscriptTypegpuStorageTextureBindingLayout {
    SubscriptTypegpuStorageTextureAccess access;
    SubscriptTypegpuTextureFormat format;
    SubscriptTypegpuTextureViewDimension viewDimension;
} SubscriptTypegpuStorageTextureBindingLayout;

typedef struct SubscriptTypegpuBindGroupLayoutEntry {
    uint32_t binding;
    SubscriptTypegpuShaderStage visibility;
    uint32_t bindingArraySize;
    SubscriptTypegpuBufferBindingLayout buffer;
    SubscriptTypegpuSamplerBindingLayout sampler;
    SubscriptTypegpuTextureBindingLayout texture;
    SubscriptTypegpuStorageTextureBindingLayout storageTexture;
} SubscriptTypegpuBindGroupLayoutEntry;

typedef struct SubscriptTypegpuBindGroupLayoutDescriptor {
    SubscriptTypegpuStringView label;
    size_t entriesCount;
    const SubscriptTypegpuBindGroupLayoutEntry* entries;
} SubscriptTypegpuBindGroupLayoutDescriptor;

typedef struct SubscriptTypegpuBindGroupEntry {
    uint32_t binding;
    SubscriptTypegpuBuffer _Nullable buffer;
    uint64_t offset;
    uint64_t size;
    SubscriptTypegpuSampler _Nullable sampler;
    SubscriptTypegpuTextureView _Nullable textureView;
} SubscriptTypegpuBindGroupEntry;

typedef struct SubscriptTypegpuBindGroupDescriptor {
    SubscriptTypegpuStringView label;
    SubscriptTypegpuBindGroupLayout layout;
    size_t entriesCount;
    const SubscriptTypegpuBindGroupEntry* entries;
} SubscriptTypegpuBindGroupDescriptor;

typedef struct SubscriptTypegpuPipelineLayoutDescriptor {
    SubscriptTypegpuStringView label;
    size_t bindGroupLayoutsCount;
    const SubscriptTypegpuBindGroupLayout* bindGroupLayouts;
    uint32_t immediateSize;
} SubscriptTypegpuPipelineLayoutDescriptor;

typedef struct SubscriptTypegpuConstantEntry {
    SubscriptTypegpuStringView key;
    double value;
} SubscriptTypegpuConstantEntry;

typedef struct SubscriptTypegpuComputeState {
    SubscriptTypegpuShaderModule module;
    SubscriptTypegpuStringView entryPoint;
    size_t constantsCount;
    const SubscriptTypegpuConstantEntry* constants;
} SubscriptTypegpuComputeState;

typedef struct SubscriptTypegpuComputePipelineDescriptor {
    SubscriptTypegpuStringView label;
    SubscriptTypegpuPipelineLayout _Nullable layout;
    SubscriptTypegpuComputeState compute;
} SubscriptTypegpuComputePipelineDescriptor;

typedef struct SubscriptTypegpuVertexAttribute {
    SubscriptTypegpuVertexFormat format;
    uint64_t offset;
    uint32_t shaderLocation;
} SubscriptTypegpuVertexAttribute;

typedef struct SubscriptTypegpuVertexBufferLayout {
    SubscriptTypegpuVertexStepMode stepMode;
    uint64_t arrayStride;
    size_t attributesCount;
    const SubscriptTypegpuVertexAttribute* attributes;
} SubscriptTypegpuVertexBufferLayout;

typedef struct SubscriptTypegpuVertexState {
    SubscriptTypegpuShaderModule module;
    SubscriptTypegpuStringView entryPoint;
    size_t constantsCount;
    const SubscriptTypegpuConstantEntry* constants;
    size_t buffersCount;
    const SubscriptTypegpuVertexBufferLayout* buffers;
} SubscriptTypegpuVertexState;

typedef struct SubscriptTypegpuPrimitiveState {
    SubscriptTypegpuPrimitiveTopology topology;
    SubscriptTypegpuIndexFormat stripIndexFormat;
    SubscriptTypegpuFrontFace frontFace;
    SubscriptTypegpuCullMode cullMode;
    bool unclippedDepth;
} SubscriptTypegpuPrimitiveState;

typedef struct SubscriptTypegpuStencilFaceState {
    SubscriptTypegpuCompareFunction compare;
    SubscriptTypegpuStencilOperation failOp;
    SubscriptTypegpuStencilOperation depthFailOp;
    SubscriptTypegpuStencilOperation passOp;
} SubscriptTypegpuStencilFaceState;

typedef struct SubscriptTypegpuDepthStencilState {
    SubscriptTypegpuTextureFormat format;
    SubscriptTypegpuOptionalBool depthWriteEnabled;
    SubscriptTypegpuCompareFunction depthCompare;
    SubscriptTypegpuStencilFaceState stencilFront;
    SubscriptTypegpuStencilFaceState stencilBack;
    uint32_t stencilReadMask;
    uint32_t stencilWriteMask;
    int32_t depthBias;
    float depthBiasSlopeScale;
    float depthBiasClamp;
} SubscriptTypegpuDepthStencilState;

typedef struct SubscriptTypegpuMultisampleState {
    uint32_t count;
    uint32_t mask;
    bool alphaToCoverageEnabled;
} SubscriptTypegpuMultisampleState;

typedef struct SubscriptTypegpuBlendComponent {
    SubscriptTypegpuBlendOperation operation;
    SubscriptTypegpuBlendFactor srcFactor;
    SubscriptTypegpuBlendFactor dstFactor;
} SubscriptTypegpuBlendComponent;

typedef struct SubscriptTypegpuBlendState {
    SubscriptTypegpuBlendComponent color;
    SubscriptTypegpuBlendComponent alpha;
} SubscriptTypegpuBlendState;

typedef struct SubscriptTypegpuColorTargetState {
    SubscriptTypegpuTextureFormat format;
    const SubscriptTypegpuBlendState* blend;
    SubscriptTypegpuColorWriteMask writeMask;
} SubscriptTypegpuColorTargetState;

typedef struct SubscriptTypegpuFragmentState {
    SubscriptTypegpuShaderModule module;
    SubscriptTypegpuStringView entryPoint;
    size_t constantsCount;
    const SubscriptTypegpuConstantEntry* constants;
    size_t targetsCount;
    const SubscriptTypegpuColorTargetState* targets;
} SubscriptTypegpuFragmentState;

typedef struct SubscriptTypegpuRenderPipelineDescriptor {
    SubscriptTypegpuStringView label;
    SubscriptTypegpuPipelineLayout _Nullable layout;
    SubscriptTypegpuVertexState vertex;
    SubscriptTypegpuPrimitiveState primitive;
    const SubscriptTypegpuDepthStencilState* depthStencil;
    SubscriptTypegpuMultisampleState multisample;
    const SubscriptTypegpuFragmentState* fragment;
} SubscriptTypegpuRenderPipelineDescriptor;

typedef struct SubscriptTypegpuCommandEncoderDescriptor {
    SubscriptTypegpuStringView label;
} SubscriptTypegpuCommandEncoderDescriptor;

typedef struct SubscriptTypegpuRenderBundleEncoderDescriptor {
    SubscriptTypegpuStringView label;
    size_t colorFormatsCount;
    const SubscriptTypegpuTextureFormat* colorFormats;
    SubscriptTypegpuTextureFormat depthStencilFormat;
    uint32_t sampleCount;
    bool depthReadOnly;
    bool stencilReadOnly;
} SubscriptTypegpuRenderBundleEncoderDescriptor;

typedef struct SubscriptTypegpuQuerySetDescriptor {
    SubscriptTypegpuStringView label;
    SubscriptTypegpuQueryType type;
    uint32_t count;
} SubscriptTypegpuQuerySetDescriptor;

typedef struct SubscriptTypegpuOrigin3D {
    uint32_t x;
    uint32_t y;
    uint32_t z;
} SubscriptTypegpuOrigin3D;

typedef struct SubscriptTypegpuTexelCopyTextureInfo {
    SubscriptTypegpuTexture texture;
    uint32_t mipLevel;
    SubscriptTypegpuOrigin3D origin;
    SubscriptTypegpuTextureAspect aspect;
} SubscriptTypegpuTexelCopyTextureInfo;

typedef struct SubscriptTypegpuTexelCopyBufferLayout {
    uint64_t offset;
    uint32_t bytesPerRow;
    uint32_t rowsPerImage;
} SubscriptTypegpuTexelCopyBufferLayout;

typedef struct SubscriptTypegpuTextureViewDescriptor {
    SubscriptTypegpuStringView label;
    SubscriptTypegpuTextureFormat format;
    SubscriptTypegpuTextureViewDimension dimension;
    uint32_t baseMipLevel;
    uint32_t mipLevelCount;
    uint32_t baseArrayLayer;
    uint32_t arrayLayerCount;
    SubscriptTypegpuTextureAspect aspect;
    SubscriptTypegpuTextureUsage usage;
} SubscriptTypegpuTextureViewDescriptor;

typedef struct SubscriptTypegpuCommandBufferDescriptor {
    SubscriptTypegpuStringView label;
} SubscriptTypegpuCommandBufferDescriptor;

typedef struct SubscriptTypegpuPassTimestampWrites {
    SubscriptTypegpuQuerySet querySet;
    uint32_t beginningOfPassWriteIndex;
    uint32_t endOfPassWriteIndex;
} SubscriptTypegpuPassTimestampWrites;

typedef struct SubscriptTypegpuComputePassDescriptor {
    SubscriptTypegpuStringView label;
    const SubscriptTypegpuPassTimestampWrites* timestampWrites;
} SubscriptTypegpuComputePassDescriptor;

typedef struct SubscriptTypegpuColor {
    double r;
    double g;
    double b;
    double a;
} SubscriptTypegpuColor;

typedef struct SubscriptTypegpuRenderPassColorAttachment {
    SubscriptTypegpuTextureView _Nullable view;
    uint32_t depthSlice;
    SubscriptTypegpuTextureView _Nullable resolveTarget;
    SubscriptTypegpuLoadOp loadOp;
    SubscriptTypegpuStoreOp storeOp;
    SubscriptTypegpuColor clearValue;
} SubscriptTypegpuRenderPassColorAttachment;

typedef struct SubscriptTypegpuRenderPassDepthStencilAttachment {
    SubscriptTypegpuTextureView view;
    SubscriptTypegpuLoadOp depthLoadOp;
    SubscriptTypegpuStoreOp depthStoreOp;
    float depthClearValue;
    bool depthReadOnly;
    SubscriptTypegpuLoadOp stencilLoadOp;
    SubscriptTypegpuStoreOp stencilStoreOp;
    uint32_t stencilClearValue;
    bool stencilReadOnly;
} SubscriptTypegpuRenderPassDepthStencilAttachment;

typedef struct SubscriptTypegpuRenderPassDescriptor {
    SubscriptTypegpuStringView label;
    size_t colorAttachmentsCount;
    const SubscriptTypegpuRenderPassColorAttachment* colorAttachments;
    const SubscriptTypegpuRenderPassDepthStencilAttachment* depthStencilAttachment;
    SubscriptTypegpuQuerySet _Nullable occlusionQuerySet;
    const SubscriptTypegpuPassTimestampWrites* timestampWrites;
} SubscriptTypegpuRenderPassDescriptor;

typedef struct SubscriptTypegpuTexelCopyBufferInfo {
    SubscriptTypegpuTexelCopyBufferLayout layout;
    SubscriptTypegpuBuffer buffer;
} SubscriptTypegpuTexelCopyBufferInfo;

typedef struct SubscriptTypegpuRenderBundleDescriptor {
    SubscriptTypegpuStringView label;
} SubscriptTypegpuRenderBundleDescriptor;

typedef struct SubscriptTypegpuDeviceDescriptor {
    SubscriptTypegpuStringView label;
    size_t requiredFeaturesCount;
    const SubscriptTypegpuFeatureName* requiredFeatures;
    const SubscriptTypegpuLimits* requiredLimits;
    SubscriptTypegpuQueueDescriptor defaultQueue;
} SubscriptTypegpuDeviceDescriptor;

typedef struct SubscriptTypegpuShaderModuleDescriptor {
    SubscriptTypegpuStringView label;
    SubscriptTypegpuStringView code;
} SubscriptTypegpuShaderModuleDescriptor;

/* Facade-owned future identifier (monotonically increasing, never 0). */
typedef uint64_t SubscriptTypegpuFutureId;

/* Creates an instance with no descriptor. */
SubscriptTypegpuInstance subscript_typegpu_create_instance(void);
void subscript_typegpu_instance_process_events(SubscriptTypegpuInstance instance);
void subscript_typegpu_instance_release(SubscriptTypegpuInstance instance);



SubscriptTypegpuFutureId subscript_typegpu_instance_request_adapter(SubscriptTypegpuInstance instance);

/*
 * 0 = pending, 1 = success, negative = failed (the negated backend
 * status enum value); -100 = unknown future id.
 */
int32_t subscript_typegpu_future_status(SubscriptTypegpuInstance instance, SubscriptTypegpuFutureId future);
void subscript_typegpu_future_drop(SubscriptTypegpuInstance instance, SubscriptTypegpuFutureId future);

/*
 * NULL until the future completed successfully; ownership transfers
 * once — a second take returns NULL.
 */
SubscriptTypegpuAdapter subscript_typegpu_request_adapter_take(SubscriptTypegpuInstance instance, SubscriptTypegpuFutureId future);

int32_t subscript_typegpu_adapter_get_limits(SubscriptTypegpuAdapter adapter, SubscriptTypegpuLimits* out);

bool subscript_typegpu_adapter_get_info(SubscriptTypegpuAdapter adapter, SubscriptTypegpuAdapterInfo* out);

bool subscript_typegpu_adapter_has_feature(SubscriptTypegpuAdapter adapter, SubscriptTypegpuFeatureName feature);

SubscriptTypegpuFutureId subscript_typegpu_adapter_request_device_with_descriptor(SubscriptTypegpuInstance instance, SubscriptTypegpuAdapter adapter, const SubscriptTypegpuDeviceDescriptor* descriptor);
SubscriptTypegpuDevice subscript_typegpu_request_device_take(SubscriptTypegpuInstance instance, SubscriptTypegpuFutureId future);

SubscriptTypegpuQueue subscript_typegpu_device_get_queue(SubscriptTypegpuDevice device);

void subscript_typegpu_device_destroy(SubscriptTypegpuDevice device);

void subscript_typegpu_device_set_label(SubscriptTypegpuDevice device, SubscriptTypegpuStringView label);

void subscript_typegpu_device_push_error_scope(SubscriptTypegpuDevice device, SubscriptTypegpuErrorFilter filter);

SubscriptTypegpuFutureId subscript_typegpu_device_pop_error_scope(SubscriptTypegpuDevice device);
bool subscript_typegpu_pop_error_scope_take(SubscriptTypegpuInstance instance, SubscriptTypegpuFutureId future, SubscriptTypegpuErrorRecord* out);
bool subscript_typegpu_device_next_uncaptured_error(SubscriptTypegpuDevice device, SubscriptTypegpuErrorRecord* out);
bool subscript_typegpu_device_lost_info(SubscriptTypegpuDevice device, SubscriptTypegpuLostRecord* out);

int32_t subscript_typegpu_device_get_limits(SubscriptTypegpuDevice device, SubscriptTypegpuLimits* out);

bool subscript_typegpu_device_get_adapter_info(SubscriptTypegpuDevice device, SubscriptTypegpuAdapterInfo* out);

bool subscript_typegpu_device_has_feature(SubscriptTypegpuDevice device, SubscriptTypegpuFeatureName feature);

SubscriptTypegpuBuffer subscript_typegpu_device_create_buffer(SubscriptTypegpuDevice device, const SubscriptTypegpuBufferDescriptor* descriptor);

SubscriptTypegpuTexture subscript_typegpu_device_create_texture(SubscriptTypegpuDevice device, const SubscriptTypegpuTextureDescriptor* descriptor);

SubscriptTypegpuSampler subscript_typegpu_device_create_sampler(SubscriptTypegpuDevice device, const SubscriptTypegpuSamplerDescriptor* descriptor);

SubscriptTypegpuBindGroupLayout subscript_typegpu_device_create_bind_group_layout(SubscriptTypegpuDevice device, const SubscriptTypegpuBindGroupLayoutDescriptor* descriptor);

SubscriptTypegpuBindGroup subscript_typegpu_device_create_bind_group(SubscriptTypegpuDevice device, const SubscriptTypegpuBindGroupDescriptor* descriptor);

SubscriptTypegpuPipelineLayout subscript_typegpu_device_create_pipeline_layout(SubscriptTypegpuDevice device, const SubscriptTypegpuPipelineLayoutDescriptor* descriptor);

SubscriptTypegpuShaderModule subscript_typegpu_device_create_shader_module(SubscriptTypegpuDevice device, const SubscriptTypegpuShaderModuleDescriptor* descriptor);

SubscriptTypegpuComputePipeline subscript_typegpu_device_create_compute_pipeline(SubscriptTypegpuDevice device, const SubscriptTypegpuComputePipelineDescriptor* descriptor);

SubscriptTypegpuFutureId subscript_typegpu_device_create_compute_pipeline_async_begin(SubscriptTypegpuInstance instance, SubscriptTypegpuDevice device, const SubscriptTypegpuComputePipelineDescriptor* descriptor);
SubscriptTypegpuComputePipeline subscript_typegpu_create_compute_pipeline_async_take(SubscriptTypegpuInstance instance, SubscriptTypegpuFutureId future);

SubscriptTypegpuRenderPipeline subscript_typegpu_device_create_render_pipeline(SubscriptTypegpuDevice device, const SubscriptTypegpuRenderPipelineDescriptor* descriptor);

SubscriptTypegpuFutureId subscript_typegpu_device_create_render_pipeline_async_begin(SubscriptTypegpuInstance instance, SubscriptTypegpuDevice device, const SubscriptTypegpuRenderPipelineDescriptor* descriptor);
SubscriptTypegpuRenderPipeline subscript_typegpu_create_render_pipeline_async_take(SubscriptTypegpuInstance instance, SubscriptTypegpuFutureId future);

SubscriptTypegpuCommandEncoder subscript_typegpu_device_create_command_encoder(SubscriptTypegpuDevice device, const SubscriptTypegpuCommandEncoderDescriptor* descriptor);

SubscriptTypegpuRenderBundleEncoder subscript_typegpu_device_create_render_bundle_encoder(SubscriptTypegpuDevice device, const SubscriptTypegpuRenderBundleEncoderDescriptor* descriptor);

SubscriptTypegpuQuerySet subscript_typegpu_device_create_query_set(SubscriptTypegpuDevice device, const SubscriptTypegpuQuerySetDescriptor* descriptor);

void subscript_typegpu_queue_submit(SubscriptTypegpuQueue queue, size_t commandsCount, const SubscriptTypegpuCommandBuffer* commands);

SubscriptTypegpuFutureId subscript_typegpu_queue_on_submitted_work_done(SubscriptTypegpuInstance instance, SubscriptTypegpuQueue queue);

void subscript_typegpu_queue_write_buffer(SubscriptTypegpuQueue queue, SubscriptTypegpuBuffer buffer, uint64_t bufferOffset, size_t dataCount, const uint8_t* data);

/* bufferOffsetBytes counts bytes; dataCount counts float elements. */
void subscript_typegpu_queue_write_buffer_f32(SubscriptTypegpuQueue queue, SubscriptTypegpuBuffer buffer, uint64_t bufferOffsetBytes, size_t dataCount, const float* data);

void subscript_typegpu_queue_write_texture(SubscriptTypegpuQueue queue, const SubscriptTypegpuTexelCopyTextureInfo* dst, const SubscriptTypegpuTexelCopyBufferLayout* layout, const SubscriptTypegpuExtent3D* extent, size_t dataCount, const uint8_t* data);

void subscript_typegpu_queue_set_label(SubscriptTypegpuQueue queue, SubscriptTypegpuStringView label);

SubscriptTypegpuFutureId subscript_typegpu_buffer_map_async(SubscriptTypegpuBuffer buffer, SubscriptTypegpuMapMode mode, size_t offset, size_t size);

int32_t subscript_typegpu_buffer_read_mapped_range(SubscriptTypegpuBuffer buffer, size_t offset, size_t outCount, uint8_t* out);

/* offsetBytes counts bytes; outCount counts float elements. */
int32_t subscript_typegpu_buffer_read_mapped_range_f32(SubscriptTypegpuBuffer buffer, size_t offsetBytes, size_t outCount, float* out);

int32_t subscript_typegpu_buffer_write_mapped_range(SubscriptTypegpuBuffer buffer, size_t offset, size_t dataCount, const uint8_t* data);

void subscript_typegpu_buffer_set_label(SubscriptTypegpuBuffer buffer, SubscriptTypegpuStringView label);

SubscriptTypegpuBufferUsage subscript_typegpu_buffer_get_usage(SubscriptTypegpuBuffer buffer);

uint64_t subscript_typegpu_buffer_get_size(SubscriptTypegpuBuffer buffer);

SubscriptTypegpuBufferMapState subscript_typegpu_buffer_get_map_state(SubscriptTypegpuBuffer buffer);

void subscript_typegpu_buffer_unmap(SubscriptTypegpuBuffer buffer);

void subscript_typegpu_buffer_destroy(SubscriptTypegpuBuffer buffer);

SubscriptTypegpuTextureView subscript_typegpu_texture_create_view(SubscriptTypegpuTexture texture, const SubscriptTypegpuTextureViewDescriptor* descriptor);

void subscript_typegpu_texture_set_label(SubscriptTypegpuTexture texture, SubscriptTypegpuStringView label);

uint32_t subscript_typegpu_texture_get_width(SubscriptTypegpuTexture texture);

uint32_t subscript_typegpu_texture_get_height(SubscriptTypegpuTexture texture);

uint32_t subscript_typegpu_texture_get_depth_or_array_layers(SubscriptTypegpuTexture texture);

uint32_t subscript_typegpu_texture_get_mip_level_count(SubscriptTypegpuTexture texture);

uint32_t subscript_typegpu_texture_get_sample_count(SubscriptTypegpuTexture texture);

SubscriptTypegpuTextureDimension subscript_typegpu_texture_get_dimension(SubscriptTypegpuTexture texture);


SubscriptTypegpuTextureFormat subscript_typegpu_texture_get_format(SubscriptTypegpuTexture texture);

SubscriptTypegpuTextureUsage subscript_typegpu_texture_get_usage(SubscriptTypegpuTexture texture);

void subscript_typegpu_texture_destroy(SubscriptTypegpuTexture texture);

void subscript_typegpu_texture_view_set_label(SubscriptTypegpuTextureView textureView, SubscriptTypegpuStringView label);

void subscript_typegpu_sampler_set_label(SubscriptTypegpuSampler sampler, SubscriptTypegpuStringView label);

void subscript_typegpu_bind_group_layout_set_label(SubscriptTypegpuBindGroupLayout bindGroupLayout, SubscriptTypegpuStringView label);

void subscript_typegpu_bind_group_set_label(SubscriptTypegpuBindGroup bindGroup, SubscriptTypegpuStringView label);

void subscript_typegpu_pipeline_layout_set_label(SubscriptTypegpuPipelineLayout pipelineLayout, SubscriptTypegpuStringView label);

void subscript_typegpu_shader_module_set_label(SubscriptTypegpuShaderModule shaderModule, SubscriptTypegpuStringView label);

SubscriptTypegpuBindGroupLayout subscript_typegpu_compute_pipeline_get_bind_group_layout(SubscriptTypegpuComputePipeline computePipeline, uint32_t groupIndex);

void subscript_typegpu_compute_pipeline_set_label(SubscriptTypegpuComputePipeline computePipeline, SubscriptTypegpuStringView label);

SubscriptTypegpuBindGroupLayout subscript_typegpu_render_pipeline_get_bind_group_layout(SubscriptTypegpuRenderPipeline renderPipeline, uint32_t groupIndex);

void subscript_typegpu_render_pipeline_set_label(SubscriptTypegpuRenderPipeline renderPipeline, SubscriptTypegpuStringView label);

SubscriptTypegpuCommandBuffer subscript_typegpu_command_encoder_finish(SubscriptTypegpuCommandEncoder commandEncoder, const SubscriptTypegpuCommandBufferDescriptor* descriptor);

SubscriptTypegpuComputePassEncoder subscript_typegpu_command_encoder_begin_compute_pass(SubscriptTypegpuCommandEncoder commandEncoder, const SubscriptTypegpuComputePassDescriptor* descriptor);

SubscriptTypegpuRenderPassEncoder subscript_typegpu_command_encoder_begin_render_pass(SubscriptTypegpuCommandEncoder commandEncoder, const SubscriptTypegpuRenderPassDescriptor* descriptor);

void subscript_typegpu_command_encoder_copy_buffer_to_buffer(SubscriptTypegpuCommandEncoder commandEncoder, SubscriptTypegpuBuffer source, uint64_t sourceOffset, SubscriptTypegpuBuffer destination, uint64_t destinationOffset, uint64_t size);

void subscript_typegpu_command_encoder_copy_buffer_to_texture(SubscriptTypegpuCommandEncoder commandEncoder, const SubscriptTypegpuTexelCopyBufferInfo* source, const SubscriptTypegpuTexelCopyTextureInfo* destination, const SubscriptTypegpuExtent3D* copySize);

void subscript_typegpu_command_encoder_copy_texture_to_buffer(SubscriptTypegpuCommandEncoder commandEncoder, const SubscriptTypegpuTexelCopyTextureInfo* source, const SubscriptTypegpuTexelCopyBufferInfo* destination, const SubscriptTypegpuExtent3D* copySize);

void subscript_typegpu_command_encoder_copy_texture_to_texture(SubscriptTypegpuCommandEncoder commandEncoder, const SubscriptTypegpuTexelCopyTextureInfo* source, const SubscriptTypegpuTexelCopyTextureInfo* destination, const SubscriptTypegpuExtent3D* copySize);

void subscript_typegpu_command_encoder_clear_buffer(SubscriptTypegpuCommandEncoder commandEncoder, SubscriptTypegpuBuffer buffer, uint64_t offset, uint64_t size);

void subscript_typegpu_command_encoder_resolve_query_set(SubscriptTypegpuCommandEncoder commandEncoder, SubscriptTypegpuQuerySet querySet, uint32_t firstQuery, uint32_t queryCount, SubscriptTypegpuBuffer destination, uint64_t destinationOffset);


void subscript_typegpu_command_encoder_insert_debug_marker(SubscriptTypegpuCommandEncoder commandEncoder, SubscriptTypegpuStringView markerLabel);

void subscript_typegpu_command_encoder_push_debug_group(SubscriptTypegpuCommandEncoder commandEncoder, SubscriptTypegpuStringView groupLabel);

void subscript_typegpu_command_encoder_pop_debug_group(SubscriptTypegpuCommandEncoder commandEncoder);

void subscript_typegpu_command_encoder_set_label(SubscriptTypegpuCommandEncoder commandEncoder, SubscriptTypegpuStringView label);

void subscript_typegpu_compute_pass_encoder_set_pipeline(SubscriptTypegpuComputePassEncoder computePassEncoder, SubscriptTypegpuComputePipeline pipeline);

void subscript_typegpu_compute_pass_encoder_set_bind_group(SubscriptTypegpuComputePassEncoder computePassEncoder, uint32_t groupIndex, SubscriptTypegpuBindGroup _Nullable group, size_t dynamicOffsetsCount, const uint32_t* dynamicOffsets);

void subscript_typegpu_compute_pass_encoder_dispatch_workgroups(SubscriptTypegpuComputePassEncoder computePassEncoder, uint32_t workgroupCountX, uint32_t workgroupCountY, uint32_t workgroupCountZ);

void subscript_typegpu_compute_pass_encoder_dispatch_workgroups_indirect(SubscriptTypegpuComputePassEncoder computePassEncoder, SubscriptTypegpuBuffer indirectBuffer, uint64_t indirectOffset);

void subscript_typegpu_compute_pass_encoder_insert_debug_marker(SubscriptTypegpuComputePassEncoder computePassEncoder, SubscriptTypegpuStringView markerLabel);

void subscript_typegpu_compute_pass_encoder_push_debug_group(SubscriptTypegpuComputePassEncoder computePassEncoder, SubscriptTypegpuStringView groupLabel);

void subscript_typegpu_compute_pass_encoder_pop_debug_group(SubscriptTypegpuComputePassEncoder computePassEncoder);

void subscript_typegpu_compute_pass_encoder_end(SubscriptTypegpuComputePassEncoder computePassEncoder);

void subscript_typegpu_compute_pass_encoder_set_label(SubscriptTypegpuComputePassEncoder computePassEncoder, SubscriptTypegpuStringView label);

void subscript_typegpu_render_pass_encoder_set_pipeline(SubscriptTypegpuRenderPassEncoder renderPassEncoder, SubscriptTypegpuRenderPipeline pipeline);

void subscript_typegpu_render_pass_encoder_set_bind_group(SubscriptTypegpuRenderPassEncoder renderPassEncoder, uint32_t groupIndex, SubscriptTypegpuBindGroup _Nullable group, size_t dynamicOffsetsCount, const uint32_t* dynamicOffsets);

void subscript_typegpu_render_pass_encoder_set_vertex_buffer(SubscriptTypegpuRenderPassEncoder renderPassEncoder, uint32_t slot, SubscriptTypegpuBuffer _Nullable buffer, uint64_t offset, uint64_t size);

void subscript_typegpu_render_pass_encoder_set_index_buffer(SubscriptTypegpuRenderPassEncoder renderPassEncoder, SubscriptTypegpuBuffer buffer, SubscriptTypegpuIndexFormat format, uint64_t offset, uint64_t size);

void subscript_typegpu_render_pass_encoder_draw(SubscriptTypegpuRenderPassEncoder renderPassEncoder, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance);

void subscript_typegpu_render_pass_encoder_draw_indexed(SubscriptTypegpuRenderPassEncoder renderPassEncoder, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t baseVertex, uint32_t firstInstance);

void subscript_typegpu_render_pass_encoder_draw_indirect(SubscriptTypegpuRenderPassEncoder renderPassEncoder, SubscriptTypegpuBuffer indirectBuffer, uint64_t indirectOffset);

void subscript_typegpu_render_pass_encoder_draw_indexed_indirect(SubscriptTypegpuRenderPassEncoder renderPassEncoder, SubscriptTypegpuBuffer indirectBuffer, uint64_t indirectOffset);

void subscript_typegpu_render_pass_encoder_set_viewport(SubscriptTypegpuRenderPassEncoder renderPassEncoder, float x, float y, float width, float height, float minDepth, float maxDepth);

void subscript_typegpu_render_pass_encoder_set_scissor_rect(SubscriptTypegpuRenderPassEncoder renderPassEncoder, uint32_t x, uint32_t y, uint32_t width, uint32_t height);

void subscript_typegpu_render_pass_encoder_set_blend_constant(SubscriptTypegpuRenderPassEncoder renderPassEncoder, const SubscriptTypegpuColor* color);

void subscript_typegpu_render_pass_encoder_set_stencil_reference(SubscriptTypegpuRenderPassEncoder renderPassEncoder, uint32_t reference);

void subscript_typegpu_render_pass_encoder_begin_occlusion_query(SubscriptTypegpuRenderPassEncoder renderPassEncoder, uint32_t queryIndex);

void subscript_typegpu_render_pass_encoder_end_occlusion_query(SubscriptTypegpuRenderPassEncoder renderPassEncoder);

void subscript_typegpu_render_pass_encoder_execute_bundles(SubscriptTypegpuRenderPassEncoder renderPassEncoder, size_t bundlesCount, const SubscriptTypegpuRenderBundle* bundles);

void subscript_typegpu_render_pass_encoder_insert_debug_marker(SubscriptTypegpuRenderPassEncoder renderPassEncoder, SubscriptTypegpuStringView markerLabel);

void subscript_typegpu_render_pass_encoder_push_debug_group(SubscriptTypegpuRenderPassEncoder renderPassEncoder, SubscriptTypegpuStringView groupLabel);

void subscript_typegpu_render_pass_encoder_pop_debug_group(SubscriptTypegpuRenderPassEncoder renderPassEncoder);

void subscript_typegpu_render_pass_encoder_end(SubscriptTypegpuRenderPassEncoder renderPassEncoder);

void subscript_typegpu_render_pass_encoder_set_label(SubscriptTypegpuRenderPassEncoder renderPassEncoder, SubscriptTypegpuStringView label);

void subscript_typegpu_command_buffer_set_label(SubscriptTypegpuCommandBuffer commandBuffer, SubscriptTypegpuStringView label);

void subscript_typegpu_render_bundle_encoder_set_pipeline(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder, SubscriptTypegpuRenderPipeline pipeline);

void subscript_typegpu_render_bundle_encoder_set_bind_group(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder, uint32_t groupIndex, SubscriptTypegpuBindGroup _Nullable group, size_t dynamicOffsetsCount, const uint32_t* dynamicOffsets);

void subscript_typegpu_render_bundle_encoder_set_vertex_buffer(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder, uint32_t slot, SubscriptTypegpuBuffer _Nullable buffer, uint64_t offset, uint64_t size);

void subscript_typegpu_render_bundle_encoder_set_index_buffer(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder, SubscriptTypegpuBuffer buffer, SubscriptTypegpuIndexFormat format, uint64_t offset, uint64_t size);

void subscript_typegpu_render_bundle_encoder_draw(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance);

void subscript_typegpu_render_bundle_encoder_draw_indexed(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t baseVertex, uint32_t firstInstance);

void subscript_typegpu_render_bundle_encoder_draw_indirect(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder, SubscriptTypegpuBuffer indirectBuffer, uint64_t indirectOffset);

void subscript_typegpu_render_bundle_encoder_draw_indexed_indirect(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder, SubscriptTypegpuBuffer indirectBuffer, uint64_t indirectOffset);

void subscript_typegpu_render_bundle_encoder_insert_debug_marker(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder, SubscriptTypegpuStringView markerLabel);

void subscript_typegpu_render_bundle_encoder_push_debug_group(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder, SubscriptTypegpuStringView groupLabel);

void subscript_typegpu_render_bundle_encoder_pop_debug_group(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder);

SubscriptTypegpuRenderBundle subscript_typegpu_render_bundle_encoder_finish(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder, const SubscriptTypegpuRenderBundleDescriptor* descriptor);

void subscript_typegpu_render_bundle_encoder_set_label(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder, SubscriptTypegpuStringView label);

void subscript_typegpu_render_bundle_set_label(SubscriptTypegpuRenderBundle renderBundle, SubscriptTypegpuStringView label);

SubscriptTypegpuQueryType subscript_typegpu_query_set_get_type(SubscriptTypegpuQuerySet querySet);

uint32_t subscript_typegpu_query_set_get_count(SubscriptTypegpuQuerySet querySet);

void subscript_typegpu_query_set_destroy(SubscriptTypegpuQuerySet querySet);

void subscript_typegpu_query_set_set_label(SubscriptTypegpuQuerySet querySet, SubscriptTypegpuStringView label);

void subscript_typegpu_query_set_release(SubscriptTypegpuQuerySet querySet);
void subscript_typegpu_render_bundle_release(SubscriptTypegpuRenderBundle renderBundle);
void subscript_typegpu_render_bundle_encoder_release(SubscriptTypegpuRenderBundleEncoder renderBundleEncoder);
void subscript_typegpu_command_buffer_release(SubscriptTypegpuCommandBuffer commandBuffer);
void subscript_typegpu_render_pass_encoder_release(SubscriptTypegpuRenderPassEncoder renderPassEncoder);
void subscript_typegpu_compute_pass_encoder_release(SubscriptTypegpuComputePassEncoder computePassEncoder);
void subscript_typegpu_command_encoder_release(SubscriptTypegpuCommandEncoder commandEncoder);
void subscript_typegpu_render_pipeline_release(SubscriptTypegpuRenderPipeline renderPipeline);
void subscript_typegpu_compute_pipeline_release(SubscriptTypegpuComputePipeline computePipeline);
void subscript_typegpu_shader_module_release(SubscriptTypegpuShaderModule shaderModule);
void subscript_typegpu_pipeline_layout_release(SubscriptTypegpuPipelineLayout pipelineLayout);
void subscript_typegpu_bind_group_release(SubscriptTypegpuBindGroup bindGroup);
void subscript_typegpu_bind_group_layout_release(SubscriptTypegpuBindGroupLayout bindGroupLayout);
void subscript_typegpu_sampler_release(SubscriptTypegpuSampler sampler);
void subscript_typegpu_texture_view_release(SubscriptTypegpuTextureView textureView);
void subscript_typegpu_texture_release(SubscriptTypegpuTexture texture);
void subscript_typegpu_buffer_release(SubscriptTypegpuBuffer buffer);
void subscript_typegpu_queue_release(SubscriptTypegpuQueue queue);
void subscript_typegpu_device_release(SubscriptTypegpuDevice device);
void subscript_typegpu_adapter_release(SubscriptTypegpuAdapter adapter);

#endif /* SUBSCRIPT_TYPEGPU_H_ */
