[package]
name = "subscript-typegpu-webgpu-gen"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "subscript-typegpu-webgpu-gen"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
toml = "0.8"
weedle2 = "5"
subscript-bindgen.workspace = true
